secrets.path.file: secrets.json
logging:
  config: classpath:log4j2-dev.xml
  level:
    com.acko: DEBUG

spring:
  datasource:
    platform: postgres
    jdbc-url: jdbc:postgresql://localhost:5432/translation_db

  jpa:
    database: POSTGRESQL
    jdbc:
      batch_size: 100
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        generate_statistics: false

  cors.origins: https://www.acko.com, http://localhost:3000, http://localhost:3001, http://localhost:3002