secrets.path.file: secrets.json
logging:
  config: classpath:log4j2-dev.xml
  level:
    com.acko: DEBUG

spring:
  datasource:
    platform: postgres
    jdbc-url: jdbc:postgresql://localhost:5432/opportunity

  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        generate_statistics: false