secrets.path.file: secrets.json
spring:
  datasource:
    platform: postgres
    jdbc-url: jdbc:postgresql://localhost:5432/translation_db

  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        generate_statistics: false

logging:
  config: classpath:log4j2-dev.xml
  level:
    com.acko: DEBUG